version: "3.9"

services:
  web:
    build: .
    command: python -m todo_app 0.0.0.0:8080 
    volumes:
      - .:/aiohttp
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:14
    env_file:
      - postgres.env 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
volumes:
  postgres_data: